language: node_js
node_js:
- node
dist: trusty
sudo: required
addons:
  chrome: stable
install:
- npm install
script:
- npx ng test
deploy:
  provider: heroku
  app: booze-hunter
  on:
    repo: DaemonWill/booze-hunter
  api_key:
    secure:N1qfvJT1nsIzsW5V7Jpf50IuQWSxVemxfP059+KMtM6nz3/iijtqKQLBEAKsLVilW1WYRBPE5AcAjbR3W7a95W+mJOb0D5RC6lO4xZXkSAdNsrlTnNu7vkze3oOSJ4P96qWB3QhPVF9sfGKvF3QlMUJwXatXBoJQolm8dk0z+DVDWgTJ8DUZG76uSzhkI0jbid6GkLQtsbhiDt2ll46+SsGRbcl0936+X/GH8vbjzpdQqrBXzPJzABKJVTYC/tRtdNIrg78agy5nmlDIOFBrehcAFkte5y3R9whwtUlLiUtGYmUbdmWeBoV/mCA+H3KqAqFveraN0R4Az8yNsmsonSbervM6pcVNGH1YZNg8Gtann92OCNaA9ENxtv5M1nzitVRtHxKZWVBTjyLGTqlkJUTHjhnRMMnClXjfGZZfJYSRgvjCxQHDsroDQYoTW4O7GDD5IqWm5USW6Kdfph+jK6MmRsnti+oqAlFR73OSo+tsvqSjEJgaYYpZ+oN/7OfA0839Zj2jF8IFQA/DK4KxBWq3q5bCq7C4uqprNlpwZ+Ec3h+lKOYYHxmz5+rmNLuNDHJV61gFSZARNv3FLrfVt4/BCh57GpsSU+QBN6ruy0HBIPi6ANUi6TON5GD0zAxtBLtAqG4lD+W7w0St8Aq1lA/E56wYKxZPdmIho0pT3BI=
